### ISSUE TITLE
php版本能不强依赖8.0吗

### ISSUE THREAD

**Issue by cxjhk** [dtm-php/dtm-client#10]
我们公司用的php版本是7.4 hyperf版本2.2 也打算介入dtm  但是php版本无法推动到8.0

**Comment by huangzhhui** [comment]
暂无计划支持 7.4 及以下版本，如果有需要不妨 fork 调整下？

**Comment by diankemao** [comment]
> 暂无计划支持 7.4 及以下版本，如果有需要不妨 fork 调整下？

黄老板，这个组件是php领域的新鲜事物，不太会用，可否出一下教程？文档或者视频？

**Comment by PandaLIU-1111** [comment]
> > 暂无计划支持 7.4 及以下版本，如果有需要不妨 fork 调整下？
> 
> 黄老板，这个组件是php领域的新鲜事物，不太会用，可否出一下教程？文档或者视频？

不是已经写了demo了吗

**Comment by diankemao** [comment]
> > > 暂无计划支持 7.4 及以下版本，如果有需要不妨 fork 调整下？
> > 
> > 
> > 黄老板，这个组件是php领域的新鲜事物，不太会用，可否出一下教程？文档或者视频？
> 
> 不是已经写了demo了吗

demo看了，不够详细哦

**Comment by huangzhhui** [comment]
https://github.com/dtm-php/dtm-sample

代码都已经贴出来了，我觉得已经足够详细了

**Comment by cxjhk** [comment]
能单独开个is吗 把我这个关了吧
