### ISSUE TITLE
barrier子事务屏障是不是实现错了

### ISSUE THREAD

**Issue by kxg3030** [dtm-php/dtm-client#11]
#### 一、问题描述 
在dtm的go语言源码里面，是需要把传入Call的sql对象再次传给回调函数的，但是好像咱这个php包里面直接没有参数，这样就不能保证这个回调函数的操作在一个事务里面了。
- go源码截图

![0c5a18f829f676a52bf76622c154733](https://user-images.githubusercontent.com/48542529/161881866-ce686831-e0c8-4bd8-bd01-01baa8069e12.png)

- php源码截图

![image](https://user-images.githubusercontent.com/48542529/161882309-13eb43fd-62a8-4b93-ae5a-06230639efa5.png)

**Comment by PandaLIU-1111** [comment]
只要在你协程不切换的情况下，你使用的就是同一个链接，不需要在传递 DB 了

**Comment by kxg3030** [comment]
好的 明白了 谢谢大佬
