### ISSUE TITLE
二阶消息addPayload参数类型错误

### ISSUE THREAD

**Issue by zdywjj** [dtm-php/dtm-client#12]
DtmClient\TransContext::addPayload(): Argument #1 ($payload) must be of type array, string given, called in /hyperf-skeleton/vendor/dtm/dtm-client/src/Msg.php on line 30[147] in /hyperf-skeleton/vendor/dtm/dtm-client/src/TransContext.php
public function add(string $action, $payload)
{
    TransContext::addStep(['action' => $action]);
    TransContext::addPayload(json_encode($payload));
}
public static function addPayload(array $payload)
{
    static::setPayloads(array_merge(static::getPayloads(), $payload));
}

**Comment by PandaLIU-1111** [comment]
能提供复现的demo吗

**Comment by zdywjj** [comment]
路由：
***@***.***');
Router::addRoute(['GET',&nbsp;'POST',&nbsp;'HEAD'],'/msg/transIn',&nbsp;[App\Controller\MsgController::class,&nbsp;'transIn']);
Router::addRoute(['GET',&nbsp;'POST',&nbsp;'HEAD'],'/msg/queryPreparedB',&nbsp;[App\Controller\MsgController::class,&nbsp;'queryPreparedB']);





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dtm-php/dtm-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月8日(星期五) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dtm-php/dtm-client] 二阶消息addPayload参数类型错误 (Issue #12)





 
能提供复现的demo吗

**Comment by PandaLIU-1111** [comment]
能提供个完整的demo吗 @zdywjj

**Comment by zdywjj** [comment]
完整的demo发不过去，这个错误不用跑demo，源码就能直接看出来的。


class&nbsp;Msg&nbsp;extends&nbsp;AbstractTransaction
{
&nbsp;&nbsp;&nbsp;&nbsp;protected&nbsp;Barrier&nbsp;$barrier;

&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;__construct(ApiInterface&nbsp;$api,&nbsp;Barrier&nbsp;$barrier)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this-&gt;api&nbsp;=&nbsp;$api;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this-&gt;barrier&nbsp;=&nbsp;$barrier;
&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;add(string&nbsp;$action,&nbsp;$payload)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransContext::addStep(['action'&nbsp;=&gt;&nbsp;$action]);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransContext::addPayload(json_encode($payload));&nbsp; //这里调用方传的是string类型
&nbsp;&nbsp;&nbsp;&nbsp;}
}


class&nbsp;TransContext&nbsp;extends&nbsp;Context
{
&nbsp; &nbsp; //形参这里指定的是array类型，调用的时候传string就报错了
&nbsp; &nbsp; public&nbsp;static&nbsp;function&nbsp;addPayload(array&nbsp;$payload)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static::setPayloads(array_merge(static::getPayloads(),&nbsp;$payload));
&nbsp;&nbsp;&nbsp;&nbsp;}}


//以上只是截取了两个类的错误部份代码






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dtm-php/dtm-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 凌晨1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dtm-php/dtm-client] 二阶消息addPayload参数类型错误 (Issue #12)





 
能提供个完整的demo吗 @zdywjj

**Comment by zdywjj** [comment]
> @zdywjj 试试 #14 这个pr看看

还是不行，改成 TransContext::addPayload([json_encode($payload)]);  这样就可以了

**Comment by zdywjj** [comment]
> > @zdywjj 试试 #14 这个pr看看
> 
> 还是不行，改成 TransContext::addPayload([json_encode($payload)]); 这样就可以了
@PandaLIU-1111

**Comment by zdywjj** [comment]
还是不行，改成 TransContext::addPayload([json_encode($payload)]); 这样就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dtm-php/dtm-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dtm-php/dtm-client] 二阶消息addPayload参数类型错误 (Issue #12)





 
@zdywjj 试试 #14  这个pr看看

**Comment by zdywjj** [comment]
现在这个可以了，是我写错了，但是现在通过composer拉下来 master 的包&nbsp; 还是老的代码




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "dtm-php/dtm-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dtm-php/dtm-client] 二阶消息addPayload参数类型错误 (Issue #12)





 
@zdywjj 试试 #14  这个pr看看
