### ISSUE TITLE
子事务屏障记录barrier时可能会出现事务未提交/回滚的情况

### ISSUE THREAD

**Issue by zdywjj** [dtm-php/dtm-client#17]
public function call(callable $businessCall): bool
    {

       //此处代码省略...
        $this->DBTransaction->beginTransaction();

        try {
            $originAffected = $this->insertBarrier($transType, $gid, $branchId, $originOP, $bid, $op);
            $currentAffected = $this->insertBarrier($transType, $gid, $branchId, $op, $bid, $op);
            // for msg's DoAndSubmit, repeated insert should be rejected.
            if ($op == TransType::MSG && $currentAffected == 0) {
                throw new DuplicatedException();
            }

            if (
                ($op == Operation::BRANCH_CANCEL || $op == Operation::BRANCH_COMPENSATE) && $originAffected > 0 // null compensate
                || $currentAffected == 0// repeated request or dangled request
            ) {
                return true;  **如果此处直接返回true，则当前事务就会出现 未提交/回滚  的错误信息**
            }

            $businessCall();

            $this->DBTransaction->commit();

            return false;
        } catch (\Throwable $throwable) {
            $this->DBTransaction->rollback();
            throw $throwable;
        }

}

**Comment by PandaLIU-1111** [comment]
![image](https://user-images.githubusercontent.com/26201936/167345175-1298891d-70bc-4299-864b-b0bddea06f0a.png)
新版本已经修复了

**Comment by zdywjj** [comment]
> ![image](https://user-images.githubusercontent.com/26201936/167345175-1298891d-70bc-4299-864b-b0bddea06f0a.png) 新版本已经修复了

阿里云的镜像感觉是很老的版本了  都没更新

**Comment by PandaLIU-1111** [comment]
> > ![image](https://user-images.githubusercontent.com/26201936/167345175-1298891d-70bc-4299-864b-b0bddea06f0a.png) 新版本已经修复了
> 
> 阿里云的镜像感觉是很老的版本了 都没更新

 阿里云的同步有延迟的，换个其他的源吧
