### ISSUE TITLE
tcc  try请求的时候报DtmClient\TransContext::getTransType(): Return value must be of type string, null returned[94]

### ISSUE THREAD

**Issue by zdywjj** [dtm-php/dtm-client#18]
try请求的时候获取的请求参数是二维数组导致报错：
array(1) {
  [0]=>
  array(5) {
    ["dtm"]=>
    string(26) "127.0.0.1:36789/api/dtmsvr"
    ["gid"]=>
    string(22) "GjcKTrBn2rQHQQ87mvHzH6"
    ["branch_id"]=>
    string(2) "01"
    ["trans_type"]=>
    string(3) "tcc"
    ["op"]=>
    string(3) "try"
  }
}

cancel请求是一维数组：
array(4) {
  ["branch_id"]=>
  string(2) "01"
  ["gid"]=>
  string(22) "GjcKTrBn2rQHQQ87mvHzH6"
  ["op"]=>
  string(6) "cancel"
  ["trans_type"]=>
  string(3) "tcc"
}

**Comment by PandaLIU-1111** [comment]
@zdywjj 你指的报错事什么报错
