### ISSUE TITLE
使用子事务屏障会出现分支事务重复请求的问题

### ISSUE THREAD

**Issue by zdywjj** [dtm-php/dtm-client#19]
public function call(callable $businessCall): bool
    {
        $gid = TransContext::getGid();
        $branchId = TransContext::getBranchId();
        $transType = TransContext::getTransType();
        $op = TransContext::getOp();

        $barrierID = ++$this->barrierId;
        $bid = sprintf('%02d', $barrierID);

        $originOP = [
            Branch::BranchCancel => Branch::BranchTry,
            Branch::BranchCompensate => Branch::BranchAction,
        ][$op] ?? '';

        $this->DBTransaction->beginTransaction();

        try {
            $originAffected = $this->insertBarrier($transType, $gid, $branchId, $originOP, $bid, $op);
            $currentAffected = $this->insertBarrier($transType, $gid, $branchId, $op, $bid, $op);
            // for msg's DoAndSubmit, repeated insert should be rejected.
            if ($op == TransType::MSG && $currentAffected == 0) {
                throw new DuplicatedException();
            }

            if (
                ($op == Operation::BRANCH_CANCEL || $op == Operation::BRANCH_COMPENSATE) && $originAffected > 0 // null compensate
                || $currentAffected == 0// repeated request or dangled request
            ) {
                $this->DBTransaction->commit();
                return true;
            }

            $businessCall(); /** 这里调用回调函数进行一次请求，返回false后中间件部分会再发起一次请求 */

            $this->DBTransaction->commit();

            return false;
        } catch (\Throwable $throwable) {
            $this->DBTransaction->rollback();
            throw $throwable;
        }
    }

**Comment by PandaLIU-1111** [comment]
重复使用了 DTMMiddleware
