### ISSUE TITLE
hyperf 启动提示类型错误

### ISSUE THREAD

**Issue by pixiaoxiao** [dtm-php/dtm-client#40]
系统:Ubuntu     PHP版本:php-8.0.21   swoole:4.8.10  框架 hyperf:^3.0
 在执行 php bin/hyperf.php start 
1. DtmClient\Api\JsonRpcHttpApi 类在声明 $serviceName $protocol属性的时候 需要指明属性的类型,不然在启动的时候会提示 "Type of DtmClient\Api\JsonRpcHttpApi::$serviceName must be string (as in class Hyperf\RpcClient\AbstractServiceClient)" 错误
2. 
3. DtmClient\TransContext类的 destroy方法 需要增加返回值类型 : void ,不然也是在启动的时候 提示 "Declaration of DtmClient\TransContext::destroy(string $id) must be compatible with Hyperf\Context\Context::destroy(string $id)"

**Comment by PandaLIU-1111** [comment]
你试试 dev-3.0 分支

**Comment by pixiaoxiao** [comment]
好的
