### ISSUE TITLE
子事务屏障会出现事务重复执行的问题

### ISSUE THREAD

**Issue by zhangsansan957** [dtm-php/dtm-client#42]
# 问题
参考[dtm-php/dtm-sample](https://github.com/dtm-php/dtm-sample)的代码测试，发现使用子事务屏障时出现控制器逻辑重复执行的问题，大佬能看下不

# 实现代码
DtmMiddleware.php
```php
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $queryParams = $request->getQueryParams() ?: $request->getParsedBody();
        $headers = $request->getHeaders();
        $transType = $headers['dtm-trans_type'][0] ?? $queryParams['trans_type'] ?? null;
        $gid = $headers['dtm-gid'][0] ?? $queryParams['gid'] ?? null;
        $branchId = $headers['dtm-branch_id'][0] ?? $queryParams['branch_id'] ?? null;
        $op = $headers['dtm-op'][0] ?? $queryParams['op'] ?? null;
        $phase2Url = $headers['dtm-phase2_url'][0] ?? $queryParams['phase2_url'] ?? null;
        $dtm = $headers['dtm-dtm'][0] ?? null;

        if ($transType && $gid && $branchId && $op) {
            $this->barrier->barrierFrom($transType, $gid, $branchId, $op, $phase2Url, $dtm);
        }

        /** @var Dispatched $dispatched */
        $dispatched = $request->getAttribute(Dispatched::class);
        if ($dispatched instanceof Dispatched && ! empty($dispatched->handler->callback)) {
            $callback = $dispatched->handler->callback;

            if (is_callable($callback)) {
                // unsupported use barrier in callable
                return $handler->handle($request);
            }

            $router = $this->parserRouter($callback);
            $class = $router['class'];
            $method = $router['method'];

            $barrier = $this->config->get('dtm.barrier.apply', []);
            $businessCall = function () use ($handler, $request) {
                $handler->handle($request);
            };

            if (in_array($class . '::' . $method, $barrier) && $this->barrier->call($businessCall)) {
                return $this->response->withStatus(200);
            }
            $annotations = AnnotationCollector::getClassMethodAnnotation($class, $method);
           /** 
            * 使用子事务屏障注解后，$this->barrier->call($businessCall)返回的结果均为false，下面会再执行一次控制器逻辑，重复执行了
            **/
            if (isset($annotations[BarrierAnnotation::class]) && $this->barrier->call($businessCall)) {
                return $this->response->withStatus(200);
            }
        }

        return $handler->handle($request);
    }
```

TccController.php
```php
    #[Barrier]
    public function transAConfirm(RequestInterface $request, ResponseInterface $response): array
    {
        var_dump('A confirm');

        return [
            'dtm_result' => 'SUCCESS',
        ];
    }
```

# 调试结果
![image](https://user-images.githubusercontent.com/35619161/195049506-75d04b66-2557-40ac-a48a-6b8d0a979f24.png)

**Comment by PandaLIU-1111** [comment]
你用的是那个版本的

**Comment by zhangsansan957** [comment]
/data/project # uname -a && php -v && composer info | grep hyperf | grep dtm && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug  5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
/data/project # uname -a && php -v && composer info | grep hyperf && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug  5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
hyperf/cache                       v2.2.33 A cache component for hyperf.
hyperf/command                     v2.2.35 Command for hyperf
hyperf/config                      v2.2.33 An independent component that provides configuration container.
hyperf/context                     v2.2.33 A coroutine context library.
hyperf/contract                    v2.2.33 The contracts of Hyperf.
hyperf/database                    v2.2.33 A flexible database library.
hyperf/db                          v2.2.33
hyperf/db-connection               v2.2.33 A hyperf db connection handler for hyperf/database.
hyperf/devtool                     v2.2.33 A Devtool for Hyperf.
hyperf/di                          v2.2.33 A DI for Hyperf.
hyperf/dispatcher                  v2.2.33 A HTTP Server for Hyperf.
hyperf/engine                      v1.3.4
hyperf/event                       v2.2.33 an event manager that implements PSR-14.
hyperf/exception-handler           v2.2.33 Exception handler for hyperf
hyperf/framework                   v2.2.33 A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microservices and middlewares.
hyperf/grpc                        v2.2.33 A GRPC basic library for Hyperf.
hyperf/grpc-client                 v2.2.33 A GRPC Client for Hyperf.
hyperf/grpc-server                 v2.2.33 A GRPC Server for Hyperf.
hyperf/guzzle                      v2.2.33 Swoole coroutine handler for guzzle
hyperf/http-message                v2.2.33 microservice framework base on swoole
hyperf/http-server                 v2.2.33 A HTTP Server for Hyperf.
hyperf/ide-helper                  v2.2.33 IDE help files for Hyperf.
hyperf/json-rpc                    v2.2.33 A JSON RPC component for Hyperf RPC Server or Client.
hyperf/load-balancer               v2.2.33 A load balancer library for Hyperf.
hyperf/logger                      v2.2.33 A logger component for hyperf.
hyperf/macroable                   v2.2.33 Hyperf Macroable package which come from illuminate/macroable
hyperf/memory                      v2.2.33 An independent component that use to operate and manage memory.
hyperf/model-listener              v2.2.33 A model listener for Hyperf.
hyperf/pool                        v2.2.33 An independent universal connection pool component.
hyperf/process                     v2.2.33 A process component for hyperf.
hyperf/redis                       v2.2.33 A redis component for hyperf.
hyperf/rpc                         v2.2.33 A rpc basic library for Hyperf.
hyperf/server                      v2.2.33 A base server library for Hyperf.
hyperf/testing                     v2.2.33 Testing for hyperf
hyperf/utils                       v2.2.34 A tools package that could help developer solved the problem quickly.

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Sep 28 2022 07:14:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q  5 Jul 2022
dtls => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608


/data/project # uname -a && php -v && composer info | grep dtm && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug  5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
dtm/dtm-client                     v0.2.3  A PHP coroutine client for distributed transaction manager DTM. 分布式事务管理器 DTM 的 PHP 协程客户端

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Sep 28 2022 07:14:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q  5 Jul 2022
dtls => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by zhangsansan957** [comment]
> 你用的是那个版本的

/data/project # uname -a && php -v && composer info | grep hyperf | grep dtm && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 https://github.com/dtm-php/dtm-client/pull/1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug 5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
/data/project # uname -a && php -v && composer info | grep hyperf && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 https://github.com/dtm-php/dtm-client/pull/1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug 5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
hyperf/cache v2.2.33 A cache component for hyperf.
hyperf/command v2.2.35 Command for hyperf
hyperf/config v2.2.33 An independent component that provides configuration container.
hyperf/context v2.2.33 A coroutine context library.
hyperf/contract v2.2.33 The contracts of Hyperf.
hyperf/database v2.2.33 A flexible database library.
hyperf/db v2.2.33
hyperf/db-connection v2.2.33 A hyperf db connection handler for hyperf/database.
hyperf/devtool v2.2.33 A Devtool for Hyperf.
hyperf/di v2.2.33 A DI for Hyperf.
hyperf/dispatcher v2.2.33 A HTTP Server for Hyperf.
hyperf/engine v1.3.4
hyperf/event v2.2.33 an event manager that implements PSR-14.
hyperf/exception-handler v2.2.33 Exception handler for hyperf
hyperf/framework v2.2.33 A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microservices and middlewares.
hyperf/grpc v2.2.33 A GRPC basic library for Hyperf.
hyperf/grpc-client v2.2.33 A GRPC Client for Hyperf.
hyperf/grpc-server v2.2.33 A GRPC Server for Hyperf.
hyperf/guzzle v2.2.33 Swoole coroutine handler for guzzle
hyperf/http-message v2.2.33 microservice framework base on swoole
hyperf/http-server v2.2.33 A HTTP Server for Hyperf.
hyperf/ide-helper v2.2.33 IDE help files for Hyperf.
hyperf/json-rpc v2.2.33 A JSON RPC component for Hyperf RPC Server or Client.
hyperf/load-balancer v2.2.33 A load balancer library for Hyperf.
hyperf/logger v2.2.33 A logger component for hyperf.
hyperf/macroable v2.2.33 Hyperf Macroable package which come from illuminate/macroable
hyperf/memory v2.2.33 An independent component that use to operate and manage memory.
hyperf/model-listener v2.2.33 A model listener for Hyperf.
hyperf/pool v2.2.33 An independent universal connection pool component.
hyperf/process v2.2.33 A process component for hyperf.
hyperf/redis v2.2.33 A redis component for hyperf.
hyperf/rpc v2.2.33 A rpc basic library for Hyperf.
hyperf/server v2.2.33 A base server library for Hyperf.
hyperf/testing v2.2.33 Testing for hyperf
hyperf/utils v2.2.34 A tools package that could help developer solved the problem quickly.

swoole

Swoole => enabled
Author => Swoole Team [team@swoole.com](mailto:team@swoole.com)
Version => 4.8.8
Built => Sep 28 2022 07:14:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q 5 Jul 2022
dtls => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

/data/project # uname -a && php -v && composer info | grep dtm && php --ri swoole
Linux 2bf1a23ff287 5.10.16.3-microsoft-standard-WSL2 https://github.com/dtm-php/dtm-client/pull/1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
PHP 8.1.9 (cli) (built: Aug 5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
dtm/dtm-client v0.2.3 A PHP coroutine client for distributed transaction manager DTM. 分布式事务管理器 DTM 的 PHP 协程客户端

swoole

Swoole => enabled
Author => Swoole Team [team@swoole.com](mailto:team@swoole.com)
Version => 4.8.8
Built => Sep 28 2022 07:14:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q 5 Jul 2022
dtls => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by PandaLIU-1111** [comment]
@zhangsansan957 试一下 v0.2.4 版本

**Comment by zhangsansan957** [comment]
升级后已ok，感谢
