### ISSUE TITLE
msg 怎么没实现 QueryPrepared 的逻辑

### ISSUE THREAD

**Issue by chunhei2008** [dtm-php/dtm-client#54]
我测试 go demo 的二阶消息，如果本地事务异常进行了回滚，调用 queryPrepared 会写一个  rollback reason 的子事务屏障，
没有这个子事务屏障，或者没有调 取消全局事务，事务被 TM 超时调起就继续执行二阶段子事务

**Comment by PandaLIU-1111** [comment]
这块的逻辑我补充了一下，试试上面那个PR是否可以

**Comment by chunhei2008** [comment]
> 

应该没问题，我自己 fork 了一个公司自己维护了；

大概增加的一些特性：

1.  RedisBarrier 子事务屏障，同官方 go 的实现
2.  Barrier 增加 barrierFromRequest(ServerRequestInterface $request) 
3. Barrier 增加 RedisBarrier 的处理和 QueryPrepared 
4. 增加处理 DTM 异常的，不用强耦合 DTM 中间件，方便自己在业务中处理子事务
5. 增加到 7.4 支持

**Comment by PandaLIU-1111** [comment]
> > 
> 
> 应该没问题，我自己 fork 了一个公司自己维护了；
> 
> 大概增加的一些特性：
> 
> 1. RedisBarrier 子事务屏障，同官方 go 的实现
> 2. Barrier 增加 barrierFromRequest(ServerRequestInterface $request)
> 3. Barrier 增加 RedisBarrier 的处理和 QueryPrepared
> 4. 增加处理 DTM 异常的，不用强耦合 DTM 中间件，方便自己在业务中处理子事务
> 5. 增加到 7.4 支持

1、2、3这个情况允许的话，能否PR一个，补充一下该仓库没实现的 redis 部分
