### ISSUE TITLE
Hyperf   如何主动触发补偿

### ISSUE THREAD

**Issue by hhw2444** [dtm-php/dtm-client#57]
如题。hyperf下，如何主动触发补偿，是在控制层还是服务层

**Comment by PandaLIU-1111** [comment]
没太理解，你是想要手动补偿还是？如果指的是自动补偿的话，则是在DTM服务发起的，客户端只有在第一阶段，是与参与者交互，后面的都是请求的DTM服务，由DTM服务去做二阶段的请求或者补偿
