### ISSUE TITLE
[ERROR] Maybe you've forgotten to commit or rollback the MySQL transaction.

### ISSUE THREAD

**Issue by MastersOfWar** [dtm-php/dtm-client#6]
MySqlBarrier存在未提交事务

    public function call(callable $businessCall): bool
    {
        $gid = TransContext::getGid();
        $branchId = TransContext::getBranchId();
        $transType = TransContext::getTransType();
        $op = TransContext::getOp();

        $barrierID = ++$this->barrierId;
        $bid = sprintf('%02d', $barrierID);

        $originOP = [
            Branch::BranchCancel => Branch::BranchTry,
            Branch::BranchCompensate => Branch::BranchAction,
        ][$op] ?? '';

        $this->DBTransaction->beginTransaction();

        try {
            $originAffected = $this->insertBarrier($transType, $gid, $branchId, $originOP, $bid, $op);
            $currentAffected = $this->insertBarrier($transType, $gid, $branchId, $op, $bid, $op);
            // for msg's DoAndSubmit, repeated insert should be rejected.
            if ($op == TransType::MSG && $currentAffected == 0) {
                throw new DuplicatedException();
            }

            if (
                ($op == Operation::BRANCH_CANCEL || $op == Operation::BRANCH_COMPENSATE) && $originAffected > 0 // null compensate
                || $currentAffected == 0// repeated request or dangled request
            ) {
                $this->DBTransaction->rollback();
                return true;
            }

            $businessCall();

            $this->DBTransaction->commit();

            return false;
        } catch (\Throwable $throwable) {
            $this->DBTransaction->rollback();
            throw $throwable;
        }
    }

**Comment by PandaLIU-1111** [comment]
能提供一个复现的demo吗

**Comment by MastersOfWar** [comment]
> 能提供一个复现的demo吗

MySqlBarrier.php第58行 没有回滚事务就return了

**Comment by MastersOfWar** [comment]
demo是dtm-php/dtm-sample,url是tcc/rollbackCase

**Comment by huangzhhui** [comment]
@MastersOfWar 请确认 #7 是否解决了你的问题

**Comment by MastersOfWar** [comment]
@huangzhhui [huangzhhui](https://github.com/huangzhhui) 是的
